<?php

namespace SimpleApiRest\console;

use ReflectionClass;

class CLIController extends BaseCLI
{

    public static function generate(string $table, bool $override): void
    {
        echo PHP_EOL . CLI::clog("GENERATING CONTROLLERS", 'g') . PHP_EOL;

        $repositoryShortName = ucfirst(self::camelCase($table)) . 'Repository' . 'AutoGenerated';
        $controllerClassName = str_replace('Repository', 'Controller', $repositoryShortName);

        self::verifyInit($table, $controllerClassName, $override, APP_CONTROLLERS_FOLDER);

        $repositoryClassName = CLI::$config['repositoryNamespace'] . '\\' . $repositoryShortName;

        if (!class_exists($repositoryClassName)) {
            echo CLI::clog("Error: Class $repositoryClassName not found.", 'r') . PHP_EOL;
            return;
        }

        $modelClassName = str_replace('Repository', '', $repositoryShortName);

        $controllerContent = "<?php" . PHP_EOL . PHP_EOL;
        $controllerContent .= "namespace " . CLI::$config['controllerNamespace'] . ";" . PHP_EOL . PHP_EOL;
        $controllerContent .= "use " . CLI::$config['repositoryNamespace'] . "\\$repositoryShortName;" . PHP_EOL;
        $controllerContent .= "use SimpleApiRest\\attributes\\Route;" . PHP_EOL . PHP_EOL;
        $controllerContent .= "class $controllerClassName {" . PHP_EOL . PHP_EOL;

        $reflection = new ReflectionClass($repositoryClassName);

        $methods = self::generateMethods($reflection, lcfirst($modelClassName), $repositoryShortName);

        foreach ($methods as $methodCode) {
            $controllerContent .= PHP_TAB . $methodCode . PHP_EOL;
        }

        $controllerContent .= "}" . PHP_EOL . PHP_EOL;

        file_put_contents(APP_CONTROLLERS_FOLDER . $controllerClassName . '.php', $controllerContent);
        echo PHP_TAB . "Controller " . CLI::clog($controllerClassName, 'c') . " generated successfully!" . PHP_EOL;
    }

    private static function generateMethods(ReflectionClass $reflection, string $routes, string $repositoryClass): array
    {
        $methods = [];

        foreach ($reflection->getMethods() as $method) {
            if (!$method->isPublic() || $method->getName() == '__construct') {
                continue;
            }

            $methodName = $method->getName();

            if (stripos($methodName, 'findAll') !== false) {
                $httpMethod = 'GET';
                $route = "$routes";
                $parameters = '';
            } elseif (stripos($methodName, 'findById') !== false) {
                $httpMethod = 'GET';
                $route = "$routes/{id}";
                $parameters = "\$id";
            } elseif (stripos($methodName, 'update') !== false) {
                $httpMethod = 'PUT';
                $route = "$routes/{id}";
                $parameters = "\$id, \$data";
            } elseif (stripos($methodName, 'delete') !== false) {
                $httpMethod = 'DELETE';
                $route = "$routes/{id}";
                $parameters = "\$id";
            } else {
                $httpMethod = 'POST';
                $route = "$routes";
                $parameters = "\$data";
            }

            $methodName = ucfirst($methodName);

            $content = <<< PHP
            #[Route('$route', [Route::ROUTER_$httpMethod])]
                public function action$methodName($parameters): array
                {
                    \$result = $repositoryClass::$methodName($parameters);
                    
                    return [
                        'message' => 'Success.',
                        'data' => \$result,
                    ];
                }
            PHP;

            $methods[] = $content . PHP_EOL;
        }

        return $methods;
    }

}