<?php

namespace SimpleApiRest\console;

class CLIModel extends BaseCLI
{

    public static function generate(string $table, bool $override): void
    {
        echo PHP_EOL . CLI::clog("GENERATING MODELS", 'g') . PHP_EOL;

        $modelName = ucfirst(self::camelCase($table)) . 'Model' . 'AutoGenerated';

        self::verifyInit($table, $modelName, $override, APP_MODELS_FOLDER);

        $columns = self::getTableColumns($table);

        $modelNamespace = CLI::$config['modelNamespace'];

        $modelContent = "<?php" . PHP_EOL . PHP_EOL;
        $modelContent .= "namespace $modelNamespace;" . PHP_EOL . PHP_EOL;
        $modelContent .= "use SimpleApiRest\\rest\\Model;" . PHP_EOL . PHP_EOL;
        $modelContent .= "class $modelName extends Model" . PHP_EOL;
        $modelContent .= "{" . PHP_EOL . PHP_EOL;

        foreach ($columns as $column) {
            $dataType = self::dataType($column['Type'], $column['Null']);
            $modelContent .= PHP_TAB . "public $dataType \${$column['Field']};" . PHP_EOL;
        }

        $modelContent .= PHP_EOL;
        $modelContent .= self::props($columns);
        $modelContent .= "}" . PHP_EOL;

        file_put_contents(APP_MODELS_FOLDER . "$modelName.php", $modelContent);
        echo PHP_TAB . "Model " . CLI::clog($modelName, 'c') . " generated successfully!" . PHP_EOL;
    }

    private static function dataType(string $type, string $null): string
    {
        $dataType = 'bool';

        if (str_starts_with($type, 'int')) {
            $dataType = 'int';
        }
        if (str_starts_with($type, 'varchar') || str_starts_with($type, 'char') || str_starts_with($type, 'timestamp')) {
            $dataType = 'string';
        }
        if (str_starts_with($type, 'date') || str_starts_with($type, 'datetime')) {
            $dataType = 'string';
        }
        if (str_starts_with($type, 'enum')) {
            $dataType = 'string';
        }

        return $null == 'NO' ? $dataType : "?$dataType";
    }

    private static function props(array $columns): string
    {
        $fields = array_column($columns, 'Field');
        $props = implode("', '", $fields);

        $content = <<< PHP
            protected const PROPS = ['$props'];
        PHP;

        return $content . PHP_EOL . PHP_EOL;
    }

}