<?php

namespace SimpleApiRest\console;

class CLIRepository extends BaseCLI
{

    public static function generate(string $table, bool $override): void
    {
        echo PHP_EOL . CLI::clog("GENERATING REPOSITORIES", 'g') . PHP_EOL;

        $repositoryName = ucfirst(self::camelCase($table)) . 'Repository' . 'AutoGenerated';

        self::verifyInit($table, $repositoryName, $override, APP_REPOSITORY_FOLDER);

        $repositoryNamespace = CLI::$config['repositoryNamespace'];
        $modelNamespace = CLI::$config['modelNamespace'];

        $modelName = ucfirst(self::camelCase($table)) . 'Model';

        $columns = self::getTableColumns($table);

        $repositoryContent = "<?php" . PHP_EOL . PHP_EOL;
        $repositoryContent .= "namespace $repositoryNamespace;" . PHP_EOL . PHP_EOL;
        $repositoryContent .= "use $modelNamespace\\$modelName;" . PHP_EOL;
        $repositoryContent .= "use Ramsey\\Uuid\\Uuid;" . PHP_EOL;
        $repositoryContent .= "use SimpleApiRest\\exceptions\\NotFoundHttpException;" . PHP_EOL;
        $repositoryContent .= "use SimpleApiRest\\query\\DeleteSafeQuery;" . PHP_EOL;
        $repositoryContent .= "use SimpleApiRest\\query\\InsertSafeQuery;" . PHP_EOL;
        $repositoryContent .= "use SimpleApiRest\\query\\SelectSafeQuery;" . PHP_EOL;
        $repositoryContent .= "use SimpleApiRest\\query\\UpdateSafeQuery;" . PHP_EOL;
        $repositoryContent .= "use SimpleApiRest\\rest\\Repository;" . PHP_EOL;
        $repositoryContent .= PHP_EOL;
        $repositoryContent .= "class $repositoryName extends Repository {" . PHP_EOL . PHP_EOL;
        $repositoryContent .= self::generateTableName($table);
        $repositoryContent .= self::generateFindByIdMethod($modelName);
        $repositoryContent .= self::generateFindAllMethod($modelName);
        $repositoryContent .= self::generateCreateMethod($modelName, $columns);
        $repositoryContent .= self::generateUpdateMethod($modelName, $columns);
        $repositoryContent .= self::generateDeleteMethod();
        $repositoryContent .= "}" . PHP_EOL;

        file_put_contents(APP_REPOSITORY_FOLDER . "$repositoryName.php", $repositoryContent);
        echo PHP_TAB . "Repository " . CLI::clog($repositoryName, 'c') . " generated successfully!" . PHP_EOL;
    }

    private static function generateTableName(string $table): string
    {
        $content = <<< PHP
            protected static function tableName(): string
            {
                return '$table';
            }
        PHP;

        return $content . PHP_EOL . PHP_EOL;
    }

    private static function generateFindByIdMethod(string $modelName): string
    {
        $content = <<< PHP
            /**
             * @throws NotFoundHttpException
             */
            public static function findById(string \$uuid, bool \$throwsOnError = false): $modelName
            {
                \$data = (new SelectSafeQuery())
                    ->from(self::tableName())
                    ->data()
                    ->where('id', \$uuid)
                    ->limit(1)
                    ->execute();
        
                if (empty(\$data) && \$throwsOnError) {
                    throw new NotFoundHttpException('$modelName not found');
                }
        
                return $modelName::fromArray(array_shift(\$data));
            }
        PHP;

        return $content . PHP_EOL . PHP_EOL;
    }

    private static function generateCreateMethod(string $modelName, array $columns): string
    {
        $fields = array_column($columns, 'Field');
        $setClause = implode("," . PHP_EOL . PHP_TAB . PHP_TAB . PHP_TAB . PHP_TAB, array_map(static function($col) {
            if ($col == 'id') {
                return "'$col' => \$uuid";
            }
           return "'$col' => \$data['$col']";
        }, $fields));

        $content = <<< PHP
            /**
             * @throws NotFoundHttpException
             */
            public static function create(array \$data): $modelName
            {
                \$uuid = Uuid::uuid4()->toString();
        
                (new InsertSafeQuery())
                    ->from(self::tableName())
                    ->data([
                        $setClause
                    ])
                    ->execute();
        
                return self::findById(\$uuid);
            }
        PHP;

        return $content . PHP_EOL . PHP_EOL;
    }

    private static function generateFindAllMethod(string $modelName): string
    {
        $content = <<< PHP
            public static function findAll(): array
            {
                \$data = (new SelectSafeQuery())
                    ->from(self::tableName())
                    ->data()
                    ->execute();

                return array_map(static fn(array \$data) => $modelName::fromArray(\$data), \$data);
            }
        PHP;

        return $content . PHP_EOL .  PHP_EOL;
    }

    private static function generateUpdateMethod(string $modelName, mixed $columns): string
    {
        $fields = array_filter(array_column($columns, 'Field'), fn($field) => $field !== 'id');
        $setClause = implode("," . PHP_EOL . PHP_TAB . PHP_TAB . PHP_TAB . PHP_TAB, array_map(fn($col) => "'$col' => \$data['$col']", $fields));

        $content = <<< PHP
            /**
             * @throws NotFoundHttpException
             */
            public static function update(string \$uuid, array \$data): $modelName
            {
                unset(\$data['id']);
        
                (new UpdateSafeQuery())
                    ->from(self::tableName())
                    ->data([
                        $setClause
                    ])
                    ->where('id', \$uuid)
                    ->execute();
        
                return self::findById(\$uuid);
            }
        PHP;

        return $content . PHP_EOL . PHP_EOL;
    }

    private static function generateDeleteMethod(): string
    {
        $content = <<< PHP
            public static function delete(string \$uuid): bool
            {
                return (new DeleteSafeQuery())
                    ->from(self::tableName())
                    ->where('id', \$uuid)
                    ->execute();
            }
        PHP;

        return $content . PHP_EOL . PHP_EOL;
    }

}